### ISSUE TITLE
Copying to temporary directory breaks local includes

### ISSUE THREAD

**Issue by dstelljes** [ClickSimply/cpp-wasm-loader#7]
Given a source file like this...

```cpp
#include "someheader.h"
```

... compilation fails because **someheader.h** doesn't exist relative to the temporary copy. Seems like there are two workarounds: don't make a temporary copy, or pass the directory to the compiler (`emcc /tmp/whatever/source.c -I/path/to/source`). Happy to open a PR for either.

**Comment by Kobzol** [comment]
I guess that the temporary copy is not necessary, so it would be better to remove it. It seems like a better option than adding the source directory to the include paths, because that could break or alter the compilation in rare cases.

It would be great if you could open a PR :-) I don't have much time to look at this ATM.

**Comment by dstelljes** [comment]
Cool, thanks!
